### ISSUE TITLE
Convert hostcredentials plugin to use logrus

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-worker#246]
This seems to be the only thing that uses `log.Printf`.  I assume other logging is going somewhere else

While I'm at it, where is that :)

**Comment by djmitche** [comment]
DEBUG=* seems to show debug logging.

@jonasfj is there some other output mechanism for other ("production") log levels?

**Comment by djmitche** [comment]
Oops, just saw your irc reply.  `monitor.logLevel` is the controlling parameter.

**Comment by djmitche** [comment]
So while I'm at it, I think we should log task starts at INFO, at least.

**Comment by djmitche** [comment]
Hm, even setting monitor.logLevel to DEBUG, I still don't get debug logging - is that separate from the $DEBUG output?

**Comment by djmitche** [comment]
I see `runtime/log.go`, but that only appears to be used by its tests.  @jonasfj I'm getting the feeling this isn't done yet.  When logging's finished will you be doing a sweep to make everything use it?

**Comment by jonasfj** [comment]
1) config loaders can't use logging, because logLevel can be configured... Config loaders can return an error if something goes wrong, that should do...
2) DEBUG log is all sorts of garbage intended to be used during development... It's effectively code instrumentation... I suspect in some future we might have a compile-time build tag that disables DEBUG logging (with luck we might get the compiler to optimize out debug logging statements completely)
3) We should definitely be doing more logging with monitor... I view the DEBUG logs there as intended to be useful for debugging something that is deployed...

Note: I make DEBUG statements for some low-level things like events multiplexing a stream... Such logging is best completely disabled as it har huge overhead...

**Comment by jonasfj** [comment]
Oh, I'll have a look maybe I didn't move everything away from logrus... The intention was to use monitor everywhere...

**Comment by djmitche** [comment]
Oh, maybe you *did* move everything from logrus, and just didn't delete it?  I see that at startup you call `logrus.New`, and then there's `runtime/log.go`.  I'm mostly confused because I've not actually seen any log output aside from DEBUG :)

I would like to do some logging in the config loader since, if we have trouble with the host-secrets service, we will need to see that and be able to debug it from the logs.  Maybe monitoring could be set up earlier with some default configuration (logLevel INFO?) and then re-initialized once the config is loaded?

**Comment by djmitche** [comment]
OK, I tried to unify things a bit in #249.

**Comment by jonasfj** [comment]
I think the early logging stuff fixed this..

**Comment by djmitche** [comment]
Thanks, yes.
