### ISSUE TITLE
Problems at task completion shouldn't result in 'malformed-payload' exception

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-worker#260]
https://public-artifacts.taskcluster.net/G-zrxYbmQNuwatYgF134iw/0/public/logs/live_backing.log
```
09:54:00     INFO - Copying logs to upload dir...

# Run a custom mach command (this is typically used by action tasks to run
# harnesses in a particular way)
if [ "$CUSTOM_MACH_COMMAND" ]; then
    eval "$HOME/workspace/build/tests/mach ${CUSTOM_MACH_COMMAND}"
    exit $?
fi
+ '[' '' ']'
cleanup
+ cleanup
+ local rv=0
+ [[ -s /home/cltbld/.xsession-errors ]]
+ cp /home/cltbld/.xsession-errors /home/cltbld/artifacts/public/xsession-errors.log
+ false
+ exit 0
[taskcluster]  Artifact upload error handled. Continuing... public/logs Handler returned an error and interrupted iteration
[taskcluster:error]  malformed-payload error: Handler returned an error and interrupted iteration
```

**Comment by djmitche** [comment]
Also, note that the error handling in `engines/native/resultset.go` consumes and ignores the actual error from the handler, replacing it with this fairly content-less error message.

**Comment by jonasfj** [comment]
@djmitche is this from taskcluster-worker v0.1.0 ?
I've refactored artifact error handling since then :)

**Comment by djmitche** [comment]
It was, yes -- did your refactor address this particular problem (that a task can run for an hour and then produce `malformed-payload`)?

**Comment by jonasfj** [comment]
A task can still do that...

But `malformed-payload` in that case indicates that the bug is to do with the definition...
It won't happen often, only in cases where you use a path that contains illegal characters..

For example on windows an artifact path like `\\somewhere/###~32 4 43 tħþ]łđ<d --wdfs>><>«][@}£@®` could produce such an error... :)
I tried to produce one on linux but it's hard, you need more than 255 folder levels in your artifact path to do it...

--- 
Anyways the error code you got here looks more like bug... rather than an actual `malformed-payload`.
By far most malformed-payload error is caught upfront by JSON schema validation..

Note: in some cases we can determine that a command `['no-such-executeable', '--my-flag']` is invalid..  But we can't determine before we have downloaded the image and started it... In some cases these will be reported as task failed, while some engines is able to report them as `malformed-payload`, in which case happens after the task has already been running for some time (say downloading and extracting an image).

We report `malformed-payload` if we know for absolutely sure that the given payload could never have resulted in a successful tasks. Ie. no matter what git revisions it had cloned etc, it wouldn't have been successful.

**Comment by djmitche** [comment]
Right, it was a bug -- and that bug was caught and replaced with one of the generic error objects which eventually resolved as malformed-payload.  The bug itself is #261 -- in this issue I just want to make sure that
* such bugs are not obscured with generic error objects (as they are then impossible to debug); and
* such bugs are not resolved malformed-payload.

In this particular case, the task worked fine when re-run, so at least in 0.1.0 "absolutely sure" was not true :)

If the error handling has been so refactored that you're pretty sure none of the problems described above are possible anymore, then we can just close this issue.

**Comment by jonasfj** [comment]
Yeah, the error handling was rewritten... So it shouldn't happen again... I evened changed some of the extraction code..
